#!/usr/bin/env bash
# load balanecer haproxy install
apt-get -y update
apt-get -y upgrade
apt-get -y install haproxy
sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxyORIGINAL.cfg
cat >> /etc/haproxy/haproxy.cfg << EOF
    listen webapp 0.0.0.0:80
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server 1026-web-01 54.157.187.251 check
    server 1026-web-02 52.202.207.38 check
EOF
service haproxy restart
